spring.application.name=Custom_OAuth2_SSO

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=sunitha
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

oauth.providers.google.client-id=${GOOGLE_CLIENT_ID}
oauth.providers.google.client-secret=${GOOGLE_CLIENT_SECRET}
oauth.providers.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
oauth.providers.google.token-uri=https://oauth2.googleapis.com/token
oauth.providers.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
oauth.providers.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

oauth.providers.google.scope=openid,email,profile


oauth.providers.github.client-id=${GITHUB_CLIENT_ID}
oauth.providers.github.client-secret=${GITHUB_CLIENT_SECRET}
oauth.providers.github.authorization-uri=https://github.com/login/oauth/authorize
oauth.providers.github.token-uri=https://github.com/login/oauth/access_token
oauth.providers.github.user-info-uri=https://api.github.com/user
oauth.providers.github.redirect-uri=http://localhost:8080/login/oauth2/code/github

oauth.providers.github.scope=read:user,user:email
